# Self evaluation form

This page contains my answers to a self evaluation form.

## Teaching Skills 

For example, previous teaching experience and qualifications, classroom/online teaching, facilitating, mentoring and coaching skills, planning, assessment.

### Strengths

I am good at writing materials, running online workshops, planning & organisation of
workshops, hosting and presenting. I have run a lot of bioinformatics based
workshops. I ask my colleagues for verbal feedback on my materials and
presentations and their feedback is very encouraging. We also ask for feedback from
students via a google form (K5). The feedback is generally very positive with
emphasis on learners liking the materials and the friendly and knowledgeable
instructors (including me).
I have finished my FLTHE and I am an Associate Fellow of the Higher Education
academy.

### Areas of Development

I would like to Increase my pedagogical theory, including how to assess students. I
would like to improve my skill in running more collaborative sessions (such as
seminars). I have a good amount of teaching experience but very little official
qualifications (highest degree earned is a MSc in bioinformatics).

## Knowledge of Learning and Teaching 

For example, other teaching/training qualifications, courses/workshops attended, reading around learning, teaching and assessment, application of theory to practice.

### Strengths 

I have a lot of experience of teaching bioinformatics to postgrads and ECRs (7 years).
This has involved Leading, Co-leading, or instructing in 40 workshops that last
between 1-4 days (mostly 2 days) (A2). Additionally, I have created and run my own
“R for Everyone” online workshop through Continuing Education 3 times since 2020
(A1). This is an evening course held for 2 hours once a week over 8 weeks.

I am keen to learn to become a better teacher and have attended the FLTHE course
and a “Train the trainers” workshop in Stockholm (A5).

### Areas of Development 

I would like to improve my pedagogical knowledge and gain higher teaching
qualifications. I hope to continue into the MA of Academic Practice after the PGCAP. I
would also like to gain a better understanding of other types of teaching and the
aspects of academic teaching I do not know (organising modules, assessment etc).

## Characteristics of a lecturer 

For example, qualities, knowledge and skills you bring to teaching - subject knowledge,
inspiring students, active learning, time management, willingness to try out new approaches.

### Strengths 

I can create a good online teaching environment by using technology to try to break
the distance (K4). Since 2020 I have developed my digital teaching skills and tools
and I am constantly trying to learn more. This has involved learning how to create
digital books via bookdown to make attractive and visually pleasing HTML
documents. I host these on the CGR server so learners can easily open these up via a
link. I have learnt to use github so I can collaborate on making these bookdowns with
my colleagues. I have learnt to use a streaming program called OBS that allows me to
switch what I am showing easily so I can change from only a webcam to my
presentation to a screen that I can live code on. I now also use Slack as a good text
frum for my workshops.

I am very knowledgeable in my field and have a passion to teach it well (K1).
Although I have a MSc in Bioinformatics I would say I learnt most of my skills on the
job and so I know how frustrating it can be to learn. Working for genomic centres as
a bioinformatician means I am carrying out analysis of lots of different datasets. This
gives me a good breadth of knowledge , useful for teaching lots of different
bioinformatic workflows. Throughout my career I have worked on at least 50
different projects varying from viral to butterfly genomics.

I am generally quite empathetic and try to not take the things I know for granted.

I am well organised with good time management skills. I always ensure to have lists
of tasks to do as I do not have the best memory so I have had to keep notes like this
for all my life. Although I am paid for 100% NEOF training workshops I also carry out
CGR projects, solely design and run CGR workshops, teach undergraduates, HPC
administration. In essence it is like I am carrying out 2 jobs whilst only working 4 days
a week.

### Areas of Development 

I can sometimes get annoyed when learners ask questions that are covered in the
materials. I try my best to not get annoyed or at least not show my annoyance.
Gaining some more patience for this would be good.
I find it difficult to motivate unmotivated learners. Some learners are happy with my
explanation as to why bioinformatics is important. However, I have met many
undergrad biological students who do not like bioinformatics at all. Many go into
biology with an interest in field or lab work so they do not think computational
knowledge will be needed. Convincing them that bioinformatics is important can be
difficult and I would like to know how to motivate them aside from the threat of low
grades and job prospects. Unfortunately even with all the reason in the world, when
someone hears an answer they do not like they tend to ignore it.
I do not have much experience of being a formal leader of colleagues. Having more
confidence when doing this would be good. I generally do not like to bother people
so I have some issues with delegation of tasks if people are not happy to volunteer.

## Subject Knowledge and other relevant skills, attributes 

For example, range and depth of subject knowledge, both own subject and learning and teaching, interpersonal skills, communication skills.

### Strengths

I have a broad knowledge of bioinformatics with a deeper knowledge in microbial
bioinformatics. This initially comes from a BSc in Microbiology and MSc in
Bioinformatics which has developed throughout my work.

I consider myself a good self taught teacher. I receive very good feedback from
learners, colleagues, and my bosses. This comes from feedback that I ask for verbally
and via learner feedback forms (K5).

I am a good public speaker and host. I know the importance of rehearsing
presentations prior to giving them. I enjoy the spotlight and would say I have a
certain charm. Our workshop feedback regularly has comments on how friendly the
teachers are and how our workshops have succeeded where other workshops (from
other providers) have failed.

### Areas of Development 

There are knowledge and skill gaps I have in my field that would be good to improve.
This involves some advanced topics such as machine learning, and certain languages
I am not confident in (e.g. python). These are becoming more important in the field
and learners are requesting these via our feedback form.

My greatest weakness in interpersonal skills is my conflict management as I try to
avoid conflict. More and more I know it is an important skill in work and teaching.
Due to cultural or language differences learners can come across as aggressive. For
example I recently had a learner who would start by saying he wanted to argue with
me but then ask me a normal question or for my assistance. Being able to identify
real conflict and knowing how to manage it would be a very useful skill to maintain a
comfortable, inclusive, and safe environment for everyone.

## Professional Skills Framework

Please read and reflect on the Areas of Activity on page 3 of the UK Professional Standards Framework to complete this section.

### Strengths 

A1: I design and plan workshops that last from 1-4 days. I run these more than once
a month.

A2: I teach and support learning via workshops for postgrads and modules for
undergraduates.

A4: I use very appropriate methods for teaching online workshops. This is through
the use of HTML books, slack, zoom, OBS, and webVNCs (browser based virtual
computers). OBS allows me to quickly change what I am showing so I can
host,present, show code etc.

A5: I have started on improving my pedagogy through completion of FLTHE and
moving onto this PGCAP. I try to keep up with literature and new tools and methods
in my field.

### Areas of Development 

A3: I currently only provide verbal feedback to learners. I want to incorporate MCQs
into my HTML bookdowns so learners can see how well they are understanding the
materials. If they do not get it correct I would like there to be a dropdown box that
will elucidate the correct answer. When/if I get more involved in undergraduate
teaching I would like to know how to effectively provide feedback. Other ways to
provide feedback would be useful to know.

A4: Providing continuing support to learners can be difficult in a workshop format. It
would be nice to know how I can accommodate continued guidance. Currently we
leave the Slack channel open for the workshops so people can ask us questions but
they have never used this. We also have started organising times when previous
workshop learners can have a 1 to 1 with one of us. This is so we can try to help
them in their current analysis.

## Reflection

Reflect on the completion of the Part One of the self-evaluation; justify your decisions with regards to your current
learning, teaching and assessment practices. Please also think about D2 of the UKPSF (page 5) to identify scope for
enhancement with some clear action points (no more than 500 words)

I am happy with my current teaching skills and practice. I design and run bioinformatics-based online workshops
(A1, A2). We send out feedback forms to our workshop attendees and we generally get very positive feedback. I
definitely have room for improvement and am aiming to formalise my teaching skills and qualifications via this
PGCAP and beyond.

An advantage of online workshops is that we can run them over 2 days split in the middle by a break day. The
workshops run from 10-4pm. I find that having shorter than full days and having a break day helps reduce cognitive
load.

I primarily focus my workshops on the learners following a HTML which contains theory, practice, and exercises. I
chose this method as active learning is a good way to teach practical skills, such as bioinformatics (K2, K3). The
HTML book I create with R bookdown is a quick way to make well formatted documents whilst including figures. A
well structured, visually pleasing document that can be read on a phone, tablet, or screen, makes reading and
absorbing the information easier.

An important part of teaching is creating a suitable teaching environment. I try a “smart casual” environment. I want
to present myself as “smart” so the learners trust my expertise and knowledge. I also want to be “casual” so learners
are comfortable to ask questions. This helps create a collaborative environment (V2).

To create an accessible online environment I utilise Slack, Zoom, and OBS (A4, K4). Slack works as a good text hub
whilst Zoom is a good place for voice and video. I utilise OBS as a streaming tool so I can change what I am showing
so I can present, then show a terminal to live code quickly. This allows me to carry out improvisational teaching. We
use a webVNC for our coding workshops. This is a link that the learner can open in their browser to use our virtual
computers with all required tools installed. It allows us to log into their virtual computer so we can see their code
and help them with issues.

I am in a slightly different position to many other academic teachers. I primarily teach postgrad, ECRs, and other
academics via workshops. I am therefore missing a lot of experience that others have.

I plan to improve my teaching with the PGCAP and with the following action plan alongside it:

- Include formative assessment in the online materials via MCQs and drop down help boxes.
- Learn new bioinformatics skills/knowledge that learners want/need.
- Improve my conflict management skills and patience.
- Improve my pedagogical knowledge.
- Provide better formative feedback to learners.
- Learn how to motivate learners better.

A big reason for attending this course is to gain a qualification. Qualifications can be useful as a shorthand for
learners and other colleagues to respect your skills. This can be an issue when you do not have a PhD (which I do
not). Ultimately, I want to teach to the best of my ability and create inclusive and effective learning environments.

## Literature
What key pedagogic literature have you read/or intend to read to support you with your teaching practices?

For my FLTHE I read the following literature (A5):

- Gross, D., Pietri, E. S., Anderson, G., Moyano-Camihort, K., & Graham, M. J. (2015). Increased preclass preparation
underlies student outcome improvement in the flipped classroom. CBE—Life Sciences Education, 14(4), ar36.
- Hackathorn, J., Solomon, E. D., Blankmeyer, K. L., Tennial, R. E., & Garczynski, A. M. (2011). Learning by Doing: An
- Empirical Study of Active Teaching Techniques. Journal of Effective Teaching, 11(2), 40-54.
- Heryandi, Y., Said, I., & Herlina, R. (2020). Online teaching in writing by means of Slack application. Journal of English
Education and Teaching, 4(1), 49-68.
- Massoudi, D., Koh, S., Hancock, P. J., & Fung, L. (2017). The effectiveness of usage of online multiple choice questions
on student performance in introductory accounting. Issues in Accounting Education, 32(4), 1-17.
- Mayer, R. E., & Chandler, P. (2001). When learning is just a click away: Does simple user interaction foster deeper
understanding of multimedia messages?. Journal of educational psychology, 93(2), 390.
- Mayer, R. E., & Moreno, R. (2003). Nine ways to reduce cognitive load in multimedia learning. Educational
psychologist, 38(1), 43-52.
- Miller-Day, M., Hecht, M. L., Krieger, J. L., Pettigrew, J., Shin, Y., & Graham, J. (2015). Teacher narratives and student
engagement: Testing narrative engagement theory in drug prevention education. Journal of language and social
psychology, 34(6), 604-620.
- National Academies of Sciences, Engineering, and Medicine. (2018). How people learn II: Learners, contexts, and
cultures. National Academies Press.
- Passera, S. (2015, August). Beyond the wall of text: How information design can make contracts user-friendly. In
- International Conference of Design, User Experience, and Usability (pp. 341-352). Springer, Cham.
- Simonds, B. K., Meyer, K. R., Quinlan, M. M., & Hunt, S. K. (2006). Effects of instructor speech rate on student
affective learning, recall, and perceptions of nonverbal immediacy, credibility, and clarity. Communication Research
Reports, 23(3), 187-197.
- Sorensen, N. (2017). Improvisation and teacher expertise: implications for the professional development of
outstanding teachers. Professional Development in Education, 43(1), 6-22.
- Strelkov, N. O., & Krutskikh, V. V. (2021, March). Usage of RMarkdown and Bookdown for Educational and Scientific
- Writing. In 2021 3rd International Youth Conference on Radio Electronics, Electrical and Power Engineering (REEPE)
(pp. 1-6). IEEE.
- Tullis, J. G., & Benjamin, A. S. (2011). On the effectiveness of self-paced learning. Journal of memory and language,
64(2), 109-118.
- Van Leeuwen, A., & Janssen, J. (2019). A systematic review of teacher guidance during collaborative learning in
primary and secondary education. Educational Research Review, 27, 71-89.
- During this PGCAP I intend to find papers to read based on the task. I would like to read the The Lecturer's Toolkit
- A Practical Guide to Assessment, Learning and Teaching By Phil Race. I read one chapter for the 1st part of the FLTHE
and found it an interesting and very readable book.