# (APPENDIX) Appendix {-}

# UKSPF

The UKSPF is the United Kingdom Professional Standards Framework for teaching and supporting learning in higher education.

The PSF has global recognition for raising the profile of teaching and learning in higher education. 

[Advance HE webpage](https://advance-he.ac.uk/knowledge-hub/professional-standards-framework-teaching-and-supporting-learning-higher-education-0)

It has three areas and four sets of descriptors that are mentioned numerous times throughout the portfolio.

## Dimensions of the framework

### Professional Values

In your context, show how you:

- __V1__: Respect individual learners and diverse groups of learners
- __V2__: Promote engagement in learning and equity of opportunity for all to reach their potential
- __V3__: Use scholarship, or research, or professional learning, or other evidence-informed approaches as a basis for effective practice
- __V4__: Respond to the wider context in which higher education operates, recognising implications for practice
- __V5__: collaborate with others to enhance practice

### Core Knowledge

- __K1__: how learners learn, generally and	within	specific	subjects
- __K2__: Approaches to teaching and/or supporting learning, appropriate for	subjects	and	level	of	study
- __K3__: Critical evaluation as a basis for effective practice
- __K4__: Appropriate use of digital and/or other technologies, and resources for learning
- __K5__: Requirements for quality assurance and enhancement, and their implications for practice

### Areas of Activity

In your context, demonstrate that you:

- __A1__: Design and plan learning
- __A2__: Teach and/or support learning through appropriate approaches and environments
- __A3__: Assess and give feedback for learning
- __A4__: Support and guide learners
- __A5__: Enhance practice through own continuing professional development